# Deployment for book_catalog microservice
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog
spec:
  replicas: 2   # Set the number of pod replicas to run
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers:
      - name: book-catalog
        image: eisenlaiacr.azurecr.io/book_catalog:latest 
        imagePullPolicy: Always
        env:
        - name: DATABASE_URL
          value: "postgresql://sit722_part5_shku_user:Ya6yGolmeGYRNJkpQyoMgxC4VdixGTcj@dpg-cru95olumphs73ejn7a0-a.oregon-postgres.render.com/sit722_part5_shku"
        ports:
        - containerPort: 8000

---
# Service for book_catalog microservice
apiVersion: v1
kind: Service
metadata:
  name: book-catalog-service
spec:
  selector:
    app: book-catalog
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000  # Port exposed to the cluster
      targetPort: 8000  # Container port