# Deployment for inventory_management microservice
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management
spec:
  replicas: 2   # Set the number of pod replicas to run
  selector:
    matchLabels:
      app: inventory-management
  template:
    metadata:
      labels:
        app: inventory-management
    spec:
      containers:
      - name: inventory-management
        image: eisenlaiacr.azurecr.io/inventory_management:latest 
        imagePullPolicy: Always
        env:
        - name: DATABASE_URL
          value: "postgresql://sit722_part5_shku_user:Ya6yGolmeGYRNJkpQyoMgxC4VdixGTcj@dpg-cru95olumphs73ejn7a0-a.oregon-postgres.render.com/sit722_part5_shku"
        ports:
        - containerPort: 8001

---
# Service for inventory_management microservice
apiVersion: v1
kind: Service
metadata:
  name: inventory-management-service
spec:
  selector:
    app: inventory-management
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8001  # Port exposed to the cluster
      targetPort: 8001  # Container port