name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Triggers the workflow on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Log in to Azure Container Registry (ACR)
      - name: Log in to ACR
        uses: azure/docker-login@v1
        with:
          login-server: eisenlaiacr.azurecr.io
          username: eisenlaiacr
          password: zndW/WmabprJq9nLmWKDh4OF6afTLRJ8lOoEYG+CjB+ACRAUAyFv

      # Step 3: Build and push Docker images to ACR
      - name: Build and push book_catalog image
        run: |
          docker build -t eisenlaiacr.azurecr.io/book_catalog:latest ./book_catalog
          docker push eisenlaiacr.azurecr.io/book_catalog:latest

      - name: Build and push inventory_management image
        run: |
          docker build -t eisenlaiacr.azurecr.io/inventory_management:latest ./inventory_management
          docker push eisenlaiacr.azurecr.io/inventory_management:latest

      # Step 4: Set up Kubernetes credentials
      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: v1.21.0

      - name: Get AKS credentials
        run: az aks get-credentials --resource-group sit722_part5_rg --name sit722_part5_aks

      # Step 5: Deploy to Kubernetes
      - name: Deploy book_catalog and inventory_management
        run: |
          kubectl apply -f ./scripts/kubernetes/book-catalog_deployment.yaml
          kubectl apply -f ./scripts/kubernetes/inventory_management_deployment.yaml
